# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_extract_year.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Year(object):
    def setupUi(self, Year):
        Year.setObjectName("Year")
        Year.resize(810, 600)
        self.centralwidget = QtWidgets.QWidget(Year)
        self.centralwidget.setObjectName("centralwidget")
        self.Journallabel = QtWidgets.QLabel(self.centralwidget)
        self.Journallabel.setGeometry(QtCore.QRect(180, 160, 71, 21))
        self.Journallabel.setStyleSheet("font: 11pt \"黑体\";")
        self.Journallabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Journallabel.setObjectName("Journallabel")
        self.yearComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.yearComboBox.setGeometry(QtCore.QRect(560, 160, 69, 22))
        self.yearComboBox.setStyleSheet("font: 11pt \"黑体\";")
        self.yearComboBox.setObjectName("yearComboBox")
        self.yearComboBox.addItem("")
        self.yearLabel = QtWidgets.QLabel(self.centralwidget)
        self.yearLabel.setGeometry(QtCore.QRect(490, 160, 61, 21))
        self.yearLabel.setStyleSheet("font: 11pt \"黑体\";")
        self.yearLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yearLabel.setObjectName("yearLabel")
        self.extractButton = QtWidgets.QPushButton(self.centralwidget)
        self.extractButton.setGeometry(QtCore.QRect(370, 410, 75, 23))
        self.extractButton.setStyleSheet("font: 11pt \"黑体\";")
        self.extractButton.setObjectName("extractButton")
        self.borderLabel = QtWidgets.QLabel(self.centralwidget)
        self.borderLabel.setGeometry(QtCore.QRect(140, 120, 531, 361))
        self.borderLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.borderLabel.setText("")
        self.borderLabel.setObjectName("borderLabel")
        self.uiLabel = QtWidgets.QLabel(self.centralwidget)
        self.uiLabel.setGeometry(QtCore.QRect(320, 50, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.uiLabel.setFont(font)
        self.uiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.uiLabel.setObjectName("uiLabel")
        self.journalComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.journalComboBox.setGeometry(QtCore.QRect(260, 160, 181, 21))
        self.journalComboBox.setStyleSheet("font: 11pt \"黑体\";")
        self.journalComboBox.setObjectName("journalComboBox")
        self.journalComboBox.addItem("")
        self.promptLabel = QtWidgets.QLabel(self.centralwidget)
        self.promptLabel.setGeometry(QtCore.QRect(210, 210, 391, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.promptLabel.sizePolicy().hasHeightForWidth())
        self.promptLabel.setSizePolicy(sizePolicy)
        self.promptLabel.setStyleSheet("font: 11pt \"黑体\";")
        self.promptLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.promptLabel.setWordWrap(True)
        self.promptLabel.setObjectName("promptLabel")
        self.borderLabel.raise_()
        self.Journallabel.raise_()
        self.yearComboBox.raise_()
        self.yearLabel.raise_()
        self.extractButton.raise_()
        self.uiLabel.raise_()
        self.journalComboBox.raise_()
        self.promptLabel.raise_()
        Year.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Year)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 23))
        self.menubar.setObjectName("menubar")
        Year.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Year)
        self.statusbar.setObjectName("statusbar")
        Year.setStatusBar(self.statusbar)

        self.retranslateUi(Year)
        QtCore.QMetaObject.connectSlotsByName(Year)

    def retranslateUi(self, Year):
        _translate = QtCore.QCoreApplication.translate
        Year.setWindowTitle(_translate("Year", "按年信息抽取"))
        self.Journallabel.setText(_translate("Year", "期刊名称"))
        self.yearComboBox.setItemText(0, _translate("Year", "2018"))
        self.yearLabel.setText(_translate("Year", "年份"))
        self.extractButton.setText(_translate("Year", "抽取"))
        self.uiLabel.setText(_translate("Year", "按年信息抽取"))
        self.journalComboBox.setItemText(0, _translate("Year", "AICHE_JOURNAL"))
        self.promptLabel.setText(_translate("Year", "<html><head/><body><p>正在抽取如下期刊相应年份的信息,请稍后...</p><p>（或请选择一个期刊和年份以抽取信息）</p></body></html>"))

