# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainUi(object):
    def setupUi(self, MainUi):
        MainUi.setObjectName("MainUi")
        MainUi.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainUi)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(300, 140, 211, 411))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(20, 0, 20, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.journalButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.journalButton.setFont(font)
        self.journalButton.setStyleSheet("font: 11pt \"黑体\";")
        self.journalButton.setObjectName("journalButton")
        self.verticalLayout.addWidget(self.journalButton)
        self.yearButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.yearButton.setFont(font)
        self.yearButton.setStyleSheet("font: 11pt \"黑体\";")
        self.yearButton.setObjectName("yearButton")
        self.verticalLayout.addWidget(self.yearButton)
        self.ldaButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ldaButton.setFont(font)
        self.ldaButton.setStyleSheet("font: 11pt \"黑体\";")
        self.ldaButton.setObjectName("ldaButton")
        self.verticalLayout.addWidget(self.ldaButton)
        self.apButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.apButton.setFont(font)
        self.apButton.setStyleSheet("font: 11pt \"黑体\";")
        self.apButton.setObjectName("apButton")
        self.verticalLayout.addWidget(self.apButton)
        self.uiLabel = QtWidgets.QLabel(self.centralwidget)
        self.uiLabel.setGeometry(QtCore.QRect(310, 60, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.uiLabel.setFont(font)
        self.uiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.uiLabel.setObjectName("uiLabel")
        MainUi.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainUi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainUi.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainUi)
        self.statusbar.setObjectName("statusbar")
        MainUi.setStatusBar(self.statusbar)

        self.retranslateUi(MainUi)
        QtCore.QMetaObject.connectSlotsByName(MainUi)

    def retranslateUi(self, MainUi):
        _translate = QtCore.QCoreApplication.translate
        MainUi.setWindowTitle(_translate("MainUi", "期刊主题分析程序"))
        self.journalButton.setText(_translate("MainUi", "期刊信息获取"))
        self.yearButton.setText(_translate("MainUi", "按年信息抽取"))
        self.ldaButton.setText(_translate("MainUi", "主题词提取"))
        self.apButton.setText(_translate("MainUi", "主题词聚类"))
        self.uiLabel.setText(_translate("MainUi", "期刊主题分析程序"))

